// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Automation_Framework_Reqnroll_Nunit.Features
{
    using Reqnroll;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("To Check the Login Functionality for different user roles")]
    public partial class ToCheckTheLoginFunctionalityForDifferentUserRolesFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "To Check the Login Functionality for different user roles", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
#line 1 "LoginPage.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public static async System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public static async System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public async System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
            {
                await testRunner.OnFeatureEndAsync();
            }
            if ((testRunner.FeatureContext == null))
            {
                await testRunner.OnFeatureStartAsync(featureInfo);
            }
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public async System.Threading.Tasks.Task TestTearDownAsync()
        {
            await testRunner.OnScenarioEndAsync();
            global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC 01. Verify successful login for different user roles")]
        [NUnit.Framework.TestCaseAttribute("supportadmin", "supportadminpassword", null)]
        [NUnit.Framework.TestCaseAttribute("providerorganization", "password", null)]
        [NUnit.Framework.TestCaseAttribute("providerprescriber", "password", null)]
        [NUnit.Framework.TestCaseAttribute("providercareteammember", "password", null)]
        [NUnit.Framework.TestCaseAttribute("supplierorganization", "password", null)]
        [NUnit.Framework.TestCaseAttribute("supplierteammember", "password", null)]
        [NUnit.Framework.TestCaseAttribute("supplierteammemberreadonly", "password", null)]
        public async System.Threading.Tasks.Task TC01_VerifySuccessfulLoginForDifferentUserRoles(string user, string password, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("User", user);
            argumentsOfScenario.Add("Password", password);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC 01. Verify successful login for different user roles", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 3
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
 await testRunner.GivenAsync("the user is on the login page and check the DME logo is visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 5
 await testRunner.WhenAsync("the user validates the placeholder text for email and password fields", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 6
 await testRunner.AndAsync(string.Format("Login To DMEScripts and {0} enter the email and password {1}", user, password), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 7
 await testRunner.AndAsync("clicks on the Sign In button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 8
 await testRunner.ThenAsync("the user should not see any error messages", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 9
 await testRunner.AndAsync("the user should be successfully redirected to the DME Home page", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("TC 02. Verify error messages when login fails with invalid credentials")]
        [NUnit.Framework.TestCaseAttribute("", "", null)]
        [NUnit.Framework.TestCaseAttribute("", "Testdme@123", null)]
        [NUnit.Framework.TestCaseAttribute("DMESupportAdmin@yopmail.com", "", null)]
        [NUnit.Framework.TestCaseAttribute("wrongadmin@yopmail.com", "Test@123", null)]
        [NUnit.Framework.TestCaseAttribute("DMESupportAdmin@yopmail.com", "Wrong@123", null)]
        [NUnit.Framework.TestCaseAttribute("DMESupportAdmin@yoopmail.com", "Test@123", null)]
        [NUnit.Framework.TestCaseAttribute("dmesupportadminyopmail.com", "Test@123", null)]
        [NUnit.Framework.TestCaseAttribute("DMESupportAdmin@yopmail.com", "test@123", null)]
        [NUnit.Framework.TestCaseAttribute("DMESupportAdmin@yopmail.com", "Test123", null)]
        [NUnit.Framework.TestCaseAttribute("DMESupportAdmin@invalid.com", "Test@123", null)]
        [NUnit.Framework.TestCaseAttribute("wrong@example.com", "wrongpass", null)]
        [NUnit.Framework.TestCaseAttribute("DMESupportAdmin@yopmail.com", "!@#$%^&*", null)]
        [NUnit.Framework.TestCaseAttribute("admin@rovicare.com", "<script>", null)]
        [NUnit.Framework.TestCaseAttribute("DMESupportAdmin@yopmail.com", "pass@", null)]
        [NUnit.Framework.TestCaseAttribute("DMESupportAdmin@yopmail.com", "password@!", null)]
        [NUnit.Framework.TestCaseAttribute("%user%@rovicaretest.com", "Test@123", null)]
        [NUnit.Framework.TestCaseAttribute("DME!Support@rovicaretest.com", "Test@123", null)]
        public async System.Threading.Tasks.Task TC02_VerifyErrorMessagesWhenLoginFailsWithInvalidCredentials(string email, string passwordd, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("Email", email);
            argumentsOfScenario.Add("Passwordd", passwordd);
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("TC 02. Verify error messages when login fails with invalid credentials", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 23
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 24
 await testRunner.GivenAsync("the user is on the login page and check the DME logo is visible", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 25
 await testRunner.AndAsync(string.Format("Login To DMEScripts {0} enter the email and enter the password {1}", email, passwordd), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
 await testRunner.AndAsync("clicks on the Sign In button", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
 await testRunner.ThenAsync("error messages should be displayed on the Login Page", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
